version: "3.1"
services:
  db001:
    image: magma1/mysql57:0.0
    hostname: db001
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - /db/db001/data:/var/lib/mysql
      - /db/db001/log:/var/log/mysql
      - /db/db001/conf:/etc/percona-server.conf.d
    networks:
      - myoverlay
  db002:
    image: magma1/mysql57:0.0
    hostname: db002
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - /db/db002/data:/var/lib/mysql
      - /db/db002/log:/var/log/mysql
      - /db/db002/conf:/etc/percona-server.conf.d
    networks:
      - myoverlay
  db003:
    image: magma1/mysql57:0.0
    hostname: db003
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - /db/db003/data:/var/lib/mysql
      - /db/db003/log:/var/log/mysql
      - /db/db003/conf:/etc/percona-server.conf.d
    networks:
      - myoverlay
  orchestrator:
    image: openarkcode/orchestrator:latest
    hostname: orchestrator
    ports:
      - "3000:3000"
    networks:
      - myoverlay
  proxysql:
    image: proxysql/proxysql
    hostname: proxysql
    ports:
      - "16032:6032"
      - "16033:6033"
    volumes:
      - /db/proxysql/data:/var/lib/proxysql
      - /db/proxysql/conf/proxysql.cnf:/etc/proxysql.cnf
    networks:
      - myoverlay
  prom001:
    image: prom/prometheus-linux-amd64
    hostname: prom001
    ports:
      - "9090:9090"
    volumes:
      - /db/prom001/data:/data
      - /db/prom001/conf:/etc/prometheus
    networks:
      - myoverlay
  grafana:
    image: grafana/grafana
    hostname: grafana
    ports:
      - "13000:3000"
    networks:
      - myoverlay

networks:
  myoverlay:
    driver: overlay
    internal: true
