version: "3"

services:

  db001:
    image: mysql57:0.0
    container_name: db001
    hostname: db001
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - /db/db001/data:/var/lib/mysql
      - /db/db001/log:/var/log/mysql
      - /db/db001/conf:/etc/percona-server.conf.d
    networks:
      - mybridge

  db002:
    image: mysql57:0.0
    container_name: db002
    hostname: db002
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - /db/db002/data:/var/lib/mysql
      - /db/db002/log:/var/log/mysql
      - /db/db002/conf:/etc/percona-server.conf.d
    networks:
      - mybridge

  db003:
    image: mysql57:0.0
    container_name: db003
    hostname: db003
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - /db/db003/data:/var/lib/mysql
      - /db/db003/log:/var/log/mysql
      - /db/db003/conf:/etc/percona-server.conf.d
    networks:
      - mybridge

  orchestrator:
    image: openarkcode/orchestrator:latest
    container_name: orchestrator
    hostname: orchestrator
    ports:
      - "3000:3000"
    networks:
      - mybridge

  proxysql:
    image: proxysql/proxysql
    container_name: proxysql
    hostname: proxysql
    ports:
      - "16032:6032"
      - "16033:6033"
    volumes:
      - /db/proxysql/data:/var/lib/proxysql
      - /db/proxysql/conf/proxysql.cnf:/etc/proxysql.cnf
    networks:
      - mybridge

  prom001:
    image: prom/prometheus-linux-amd64
    container_name: prom001
    hostname: prom001
    ports:
      - "9090:9090"
    volumes:
      - /db/prom001/data:/data
      - /db/prom001/conf:/etc/prometheus
    networks:
      - mybridge

  grafana:
    image: grafana/grafana
    container_name: grafana
    hostname: grafana
    ports:
      - "13000:3000"
    networks:
      - mybridge

networks:
  mybridge:
    external: true
